### ISSUE TITLE
Feature request: Method to get valid move parameter values/ranges

### ISSUE THREAD

**Issue by sparr** [nicolodavis/boardgame.io#635] opened 2020-04-22 03:04 UTC
I want to be able to annotate a move in some way, in my game definition, that will provide feedback to a client / board / player about the expected or allowed parameter values and ranges for the move.

In games I have seen so far, a lot of this logic exists in the client/board implementation, and then for complex moves it remains possible for the player to attempt a move then find out it is INVALID_MOVE.

This feature request is meant to more solidly separate game implementation from interface. I want multiple clients to all be able to take advantage of the same code to enumerate valid moves, or at least get some information with which to narrow down the possibilities.

For a game like checkers, it would probably be possible to return an enumeration of every possible move.

For a more complex game, you might return some ranges of values, e.g. indicating that paramA can be 100-500 and paramB can be 100-200, without necessarily mentioning that B>A will return INVALID_MOVE.

**Comment by delucis** [comment] 2020-04-24 21:32
Hey @sparr I’m going to close this as a duplicate of #292, and I’ve copied your suggestions over there. Thanks!

**Closed by delucis** 2020-04-24 21:32 UTC
