### ISSUE TITLE
State desync with local multiplayer and calls to random in onTurnBegin/onPhaseBegin

### ISSUE THREAD

**Issue by dtrauma** [nicolodavis/boardgame.io#333] opened 2019-01-11 20:50 UTC
When you use local multiplayer,
and calls to ctx.random in onTurnBegin/onPhaseBegin,
and have multiple Clients on the same page,
they will desync on page load. After the first move, everything works correctly.
Perhaps related to #298 ?

See https://github.com/dtrauma/boardgame-test/tree/bug-random-local-multiplayer for a demonstration.

**Comment by nicolodavis** [comment] 2019-01-22 14:56
The problem is actually a race condition in the [logic](https://github.com/nicolodavis/boardgame.io/blob/master/src/master/master.js#L172) that handles the initial client sync with the master.

**Comment by nicolodavis** [comment] 2019-01-22 15:38
Fixed in `0.31`.

**Closed by nicolodavis** 2019-01-22 15:38 UTC
