### ISSUE TITLE
Reconnection to server and performance when connection is down

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#672] opened 2020-05-07 10:06 UTC
I'm still investigating but seems that there is some bug in way the framework handle things in case of multiplayer. Scenario : 

1. I have single player game, but as there is no other way i use multiplayer to be able to sync game state with server 
2. Lets say i have : 

```
myRandomMove: (G,ctx) => {
   ctx.events.endPhase();
   const myProp = Math.random(); 
  return { ...G, myProp } 
}; 
```
3. Lets say that i lost internet connection for a moment and in this moment i ran `myRandomMove` 

What happens? Phase is not finished, but G is updated. 

4. Connection is back. I run `myRandomMove` one more time, unfortunately `endPhase` is not called, `G` is updated one more time. 

Seems that reconnection is not handled properly as well as movs are nt handled well in case of no internet connection. Im still on version 0.28.0, going to update the version and comment this issue if problem persist.

**Comment by delucis** [comment] 2020-05-07 10:11
This is a known issue, I think, a duplicate of #218. The problem is that if a connection times out, the client still runs its optimistic update and is then out of sync with the server.

I’ll close this in favour of #218, but thanks for the report.

**Closed by delucis** 2020-05-07 10:11 UTC

**Comment by pociej** [comment] 2020-05-07 10:30
Hmm but it is critical, in fact it makes framework more or less unusable, why then it is opened from 2 years and not fixed yet?

**Comment by nicolodavis** [comment] 2020-05-07 10:40
Hi @pociej. If you are eager to see this fixed soon, feel free to contribute a PR. We haven't seen too many reports of people running into this issue which explains why a fix hasn't been prioritized.

**Comment by pociej** [comment] 2020-05-07 10:51
Hi @nicolodavis sure i could do that. If you though about this issue before let me know your thoughts and some tips, like where you want this logic to be placed. 

As i see this problem two approaches are possible
1. Do not update game state as long as there is no reply from server, thats against optimistic UI concept 
2. Allow all the flow, including events ( like end phase ) to run in the client, and then if server connection fails revert the changes in `G` and `ctx` 

Also we should make sure that on successful reconnection player is able to continue without need of manual refresh.

**Comment by nicolodavis** [comment] 2020-05-08 01:45
Something along the lines of [2] is probably good.  Maybe we can make the state changes optimistically and then if there is no response from the server just run a 'sync' similar to the one we do when a client first connects [here](https://github.com/nicolodavis/boardgame.io/blob/master/src/client/transport/socketio.js#L106)?

**Comment by pociej** [comment] 2021-01-09 20:53
@nicolodavis @delucis I had short break but now i want to back to this issue.  I see #218 is still open. Before i start this. Can I ask, how it is possible that this is still not fixed. No offence, i just see many project on your webpage that are using framework, and framework is still unable to handle reconnection, which I think i dont use too big words, makes it not usable on production with multiple players. Interesting.

**Comment by pociej** [comment] 2021-03-14 12:12
@nicolodavis @delucis any chance for update?
