### ISSUE TITLE
Problem on checking stateID on Socket.IO update action

### ISSUE THREAD

**Issue by evandroabukamel** [nicolodavis/boardgame.io#700] opened 2020-05-17 16:31 UTC
Well, I'm developing a mobile game using this library and during my tests using an external tool I found out that there's an strict comparrison for `stateID` on socketio.ts and that's causing some issues.

The problem is that some tools send raw values as string and the `stateID` value is stored as an integer on the game state so thas causes the follwing error when I send an update action:

`ERROR: invalid stateID, was=[0], expected=[0]`

I'm going to open a PR to change the stateID parameter to number if it's a string. That fixed my problem.

What do you think?

**Comment by evandroabukamel** [comment] 2020-05-17 16:49
That's strange because the same thing didn't happen for playerID.

**Comment by delucis** [comment] 2020-05-17 21:54
Hi @evandroabukamel, thanks for the report! When you say “some tools send raw values as string” which tools are these exactly? We could add some type coercion here (with `parseInt` or something), but if this is being caused by bad external input, it might be better to fix the input if possible.

**Comment by evandroabukamel** [comment] 2020-05-17 22:14
Hi, @delucis . Well, I'm using the (Firecamp)[https://firecamp.io/docs/rtc/socket-io/emitters/] tool to test the websocket, it helps a lot. I tried the parseInt on the code and it worked for me. 
Now, I'm trying to use typed parameters to see if that solves to problem too.

I believe that won't be a problem during the client implementation as we can pass typed parameters.

**Comment by delucis** [comment] 2020-05-17 22:20
Ah, OK. And Firecamp won’t allow you to send numbers?

From a quick look I’d imagine emitting something like `{ "stateID": 9 }` should keep the correct type.

Out of curiosity, what are you building the client with?

**Comment by evandroabukamel** [comment] 2020-05-17 22:34
Yeah, Firecamp doesn't allow us to send numbers, I just opened a issue on their repository. 
I tried `{ "stateID": 9 }``, it didn't worked. 
Our client is being built with Flutter, not by me. I think we can send typed parameters there.
So, let's keep this on stand-by to see if someone at Firecamp responds.
I'm goona write some code to test the websockets.

**Comment by delucis** [comment] 2020-05-17 23:00
Oh, great — I’d be curious to see the Flutter client if it’s open source.

I’ll close this for now. Feel free to re-open if you feel the need.

**Closed by delucis** 2020-05-17 23:00 UTC
