### ISSUE TITLE
Add api endpoint to list available games, stats etc...

### ISSUE THREAD

**Issue by jstacoder** [nicolodavis/boardgame.io#214] opened 2018-06-07 06:19 UTC
I think since `games` is an argument you pass to the game api server when you create it, (ie since that data is a part of the api implementation) it would be nice if it had an endpoint to list available games, and possibly stats about the players? Maybe high scores or w/e, I think I’ll issue a pull request for the game list endpoint If it sounds like a good idea?

**Comment by francoijs** [comment] 2018-08-11 18:01
I tried an implementation for a new 'list' API endpoint in the server, to list game instances:
-> at reception of a GET request with format `/games/:name`, it returns some metadata about instances for the given game name (for now metadata consists in the gameID and the list of players)
-> I also added a 'Lobby' module in the web examples to demonstrate the API endpoints for 'create' and  'list' 
[https://github.com/francoijs/boardgame.io/tree/add-game-instances-list-api-endpoint](url)

**Comment by nicolodavis** [comment] 2018-08-11 23:29
@francoijs Awosone! Feel free to send me a PR.

**Comment by francoijs** [comment] 2018-08-12 10:48
PR#256 (still some work to do on coverage and MongoDB support)

**Comment by nicolodavis** [comment] 2019-04-14 11:49
Marking this as a duplicate of #354

**Closed by nicolodavis** 2019-04-14 11:49 UTC
Labels: feature, good first issue
