### ISSUE TITLE
Plugins not accessible in turn's `onEnd` when `endTurn` called from a move

### ISSUE THREAD

**Issue by adngdb** [nicolodavis/boardgame.io#623] opened 2020-04-16 09:15 UTC
When you call `ctx.events.endTurn()` from inside a move, during the subsequent call to `onEnd`, it seems that plugins are not accessible. However, if you simply call `ctx.events.endTurn()` directly from your input, it works just fine.

## Library version

I reproduced this behavior with versions 0.39.5 and 0.39.7.

## Steps to reproduce

1. Use `ctx.events.endTurn()` in a move function.
2. Use `ctx.random.Die()` or any plugin methods inside the turn's `onEnd` callback.
3. Call your move function.

## Expected result

The plugin method is available and produces the expected results.

## Actual result

An exception is raised: ` TypeError: Cannot read property 'Die' of undefined`.

## Test case

https://codesandbox.io/s/boardgameio-uosrp

**Comment by delucis** [comment] 2020-04-16 09:36
:+1: I think this is a duplicate of #588

**Comment by adngdb** [comment] 2020-04-27 15:19
I've tried to solve this by myself, but it requires a knowledge of the engine that is a bit too deep for what I can manage now. However, I did write a test suite that reproduces the issues (from here and #588). Using them you can see the full stack leading to the exception. Hopefully that can help someone with more experience solve this? 

Here are the tests:

```js
import { Client } from './client/client';

jest.mock('./core/logger', () => ({
  info: jest.fn(),
  error: jest.fn(),
}));


describe('plugins are accessible in events triggered from moves', () => {
  test('turn/onEnd', () => {
    const game = {
      moves: {
        stop: (G, ctx) => ctx.events.endTurn(),
      },
      turn: {
        onEnd: (G, ctx) => {
          G.onEnd = ctx.random.Die(1);
        },
      },
    };

    const client = Client({ game });
    client.moves.stop();
    expect(client.getState().G).toEqual({
      onEnd: 1,
    });
  });

  test('phase/onEnd', () => {
    const game = {
      moves: {
        stop: (G, ctx) => ctx.events.endPhase(),
      },
      phases: {
        first: {
          start: true,
          onEnd: (G, ctx) => {
            G.onEnd = ctx.random.Die(1);
          },
        },
      },
    };

    const client = Client({ game });
    client.moves.stop();
    expect(client.getState().G).toEqual({
      onEnd: 1,
    });
  });

  test('phase/onBegin', () => {
    const game = {
      moves: {
        stop: (G, ctx) => ctx.events.setPhase('second'),
      },
      phases: {
        first: {
          start: true,
        },
        second: {
          onBegin: (G, ctx) => {
            G.onEnd = ctx.random.Die(1);
          },
        }
      },
    };

    const client = Client({ game });
    client.moves.stop();
    expect(client.getState().G).toEqual({
      onEnd: 1,
    });
  });
});
```

And a sample error stack:

```
   TypeError: Cannot read property 'Die' of undefined

      16 |       turn: {
      17 |         onEnd: (G, ctx) => {
    > 18 |           G.onEnd = ctx.random.Die(1);
         |                                ^
      19 |         },
      20 |       },
      21 |     };

      at Proxy.onEnd (src/plugins.test.ts:18:32)
      at Proxy.<anonymous> (node_modules/immer/src/immer.js:44:45)
      at Immer.call (node_modules/immer/src/immer.js:64:33)
      at produce (node_modules/immer/src/immer.js:44:22)
      at Object.onEnd (src/core/flow.ts:83:14)
      at EndTurn (src/core/flow.ts:506:27)
      at Process (src/core/flow.ts:200:15)
      at Object.EndTurnEvent (src/core/flow.ts:747:12)
      at Object.ProcessEvent (src/core/flow.ts:812:34)
      at Events.update (src/plugins/events/events.ts:99:22)
      at Object.dangerouslyFlushRawState (src/plugins/plugin-events.ts:22:21)
      at src/plugins/main.ts:188:22
          at Array.forEach (<anonymous>)
      at Object.<anonymous>.exports.Flush (src/plugins/main.ts:167:46)
      at src/core/reducer.ts:216:25
      at dispatch (node_modules/redux/lib/redux.js:218:22)
      at next (src/client/client.js:120:22)
      at next (src/client/client.js:170:22)
      at Object.next [as dispatch] (src/client/client.js:183:22)
      at Object.dispatch [as stop] (src/client/client.js:41:13)
      at Object.<anonymous> (src/plugins.test.ts:24:18)
```

**Closed** 2020-05-02 08:04 UTC
