### ISSUE TITLE
flow.onMove ...

### ISSUE THREAD

**Issue by pociej** [nicolodavis/boardgame.io#306] opened 2018-12-05 18:23 UTC
... is not fired at all on client when running in multiplayer mode.

**Comment by pociej** [comment] 2018-12-05 20:37
Also playerID and gameID are not accessible in `flow.onMove`. In client i know those values but as this api is exposed only server side its useless for me as i don't know there, where and by who move has been performed.

**Comment by nicolodavis** [comment] 2018-12-06 00:08
Do you have a minimal example to reproduce this?

playerID is available in the ctx object. Game logic should not need to know what the gameID is. What's your use case?

**Comment by pociej** [comment] 2018-12-06 08:11
Ok sorry, playerID is presented in ctx, but it gives me nothing. I want fire side jobs, like tell admin user that some player just moved and i want to know exactly who and where. You said
 
> Game logic should not need to know what the gameID. 

I agree but i want agree we should think about `onMove` as part of game internals. Its natural place to register callback which can do things without any impact on game state. I know i can solve my case by observing db updates or by having gameId on game state level but both solutions are very not nice. 

With `onMove` callback on client it would be easier, because on client i know gameId and i don't need to cheat on game states. About reproduction, let me make sure i understood your comment above @nicolodavis. I will need to create new repo for reproduction so wanted to be sure its unexpected behaviour and `onMove` should works client side.

**Comment by pociej** [comment] 2018-12-06 08:11
Ok sorry, playerID is presented in ctx, but it gives me nothing. I want fire side jobs, like tell admin user that some player just moved and i want to know exactly who and where. You said
 
> Game logic should not need to know what the gameID. 

I agree but i want agree we should think about `onMove` as part of game internals. Its natural place to register callback which can do things without any impact on game state. I know i can solve my case by observing db updates or by having gameId on game state level but both solutions are very not nice. 

With `onMove` callback on client it would be easier, because on client i know gameId and i don't need to cheat on game states. About reproduction, let me make sure i understood your comment above @nicolodavis. I will need to create new repo for reproduction so wanted to be sure its unexpected behaviour and `onMove` should works client side.

**Comment by nicolodavis** [comment] 2018-12-06 08:49
I think what you're looking for is a general callback mechanism that allows you to subscribe to game updates. I think that's a valid use-case that we don't have great support for at the moment.

The best thing you can do at the moment is to write Redux middleware similar to [this](https://github.com/nicolodavis/boardgame.io/blob/master/src/client/client.js#L142).  It will see all the state updates and actions passing through the system. I would discourage you from using `onMove` because it is meant to be a side-effect free function (meaning that it has to be idempotent).

About `onMove` not running client-side, that is actually expected behavior in a server-based multiplayer setting (another reason not to use it and do the Redux middleware thing I suggested instead).

**Comment by nicolodavis** [comment] 2018-12-06 09:36
This already exists, which is what I was referring to: https://boardgame.io/#/debugging

Just pass your middleware to the client via the `enhancer` field.

**Comment by pociej** [comment] 2018-12-06 09:41
Oh i see, thats exactly what i needed. Thx for you help @nicolodavis. If i can suggesting something i would change title of docs section, `enhancer` can be use for debugging but definitely not only for debugging.

**Comment by nicolodavis** [comment] 2018-12-06 10:05
Great! Yeah, I'll try to make this lesser known feature more prominent in the documentation.

If this resolves your problem for now, I'll close this issue. Feel free to continue the conversation if you run into issues of course.

**Closed by nicolodavis** 2018-12-06 10:05 UTC
